### ISSUE TITLE
Feature: User can choose coffee subscription options

### ISSUE THREAD

**Issue by btoomepuu** [btoomepuu/final-project#1]
## ⚙️ Feature

> ##### User can make selections for their coffee subscription.

## 📐 Functionality

> ##### User clicks to choose options for each question.

## 🖼️ Wireframes

![Screen Shot 2022-09-19 at 2 41 56 PM](https://user-images.githubusercontent.com/59620542/191091954-bc962478-02be-45dd-9824-141c6b0f630b.png)
38-460d-955b-0ff3d484b483.png)
![Screen Shot 2022-09-19 at 2 42 05 PM](https://user-images.githubusercontent.com/59620542/191093044-c9b617b3-7882-4138-a28d-dfffaf1a3c93.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to record coffee selections
- [ ] Update `data.sql` to update coffee selections

### ☁️ Server Tasks

- [ ] Create server rout to save users chioces to the database
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to show user options 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
